import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const products = [
  // Section A – MEP & Filtration
  {
    name: "Swimming Pool Filter",
    description: "Bobbin Wound Fiber Glass Sand Filter",
    category: "Filtration Equipment",
    sectionCode: "A",
    unit: "Nos",
    warranty: "05 Years",
    defaultRate: 45000,
    specification: "Bobbin Wound Fiber Glass Sand Filters Max. Velocity 50 m/hr. Dia: 1200D mm, Flow Rate: 12 m3/hr. (Make: Blue Laton)",
    displayOrder: 1,
  },
  {
    name: "Filter Media (Silica Sand)",
    description: "Glass Filter Media / Silica Sand",
    category: "Maintenance",
    sectionCode: "A",
    unit: "Kg",
    warranty: "N/A",
    defaultRate: 40,
    specification: "Glass Filter Media works across salt/chlorine pools; replacement for Silica Sand. (Make: Blue Laton/Pool Maxx)",
    displayOrder: 2,
  },
  {
    name: "06 Way Multiport Valve 1.5\"",
    description: "Multiport Control Valve",
    category: "Filtration Equipment",
    sectionCode: "A",
    unit: "Nos",
    warranty: "01 Years",
    defaultRate: 8500,
    specification: "06-Way control valve for maximum flow at low pressure. 7 functions: filter, backwash, waste, rinse, closed, recirculate and winterize. (Make: Blue Laton)",
    displayOrder: 3,
  },
  {
    name: "Recirculating Pump",
    description: "1.5HP Self Priming Pump",
    category: "Filtration Equipment",
    sectionCode: "A",
    unit: "Nos",
    warranty: "02 Years",
    defaultRate: 25000,
    specification: "Single Stage Self Priming Centrifugal Horizontal Pump with prefilter in Techno Polymer. Cap: 1.5HP. (Make: Blue Laton)",
    displayOrder: 4,
  },
  {
    name: "Pool Main Drain",
    description: "ABS Main Drain Grill",
    category: "Plumbing",
    sectionCode: "A",
    unit: "Nos",
    warranty: "N/A",
    defaultRate: 1800,
    specification: "Drain Grill, Rectangular 300mm x 300mm, Made of ABS White plastic. (Make: Blue Laton)",
    displayOrder: 5,
  },
  {
    name: "Wall Inlets",
    description: "ABS Wall/Floor Inlets",
    category: "Plumbing",
    sectionCode: "A",
    unit: "Nos",
    warranty: "N/A",
    defaultRate: 750,
    specification: "Floor/Wall Inlets, ABS white plastics, 50mm glue connection. Flow Rate: 4 m3/hr. (Make: Blue Laton)",
    displayOrder: 6,
  },
  {
    name: "Underwater Light",
    description: "9W RGB LED Light",
    category: "Lighting",
    sectionCode: "A",
    unit: "Nos",
    warranty: "01 Years",
    defaultRate: 3500,
    specification: "LED 9W RGB, 12V AC, 2ft Cord Wall Surface Mounted, IP68 Waterproof, Stainless Steel. (Make: Blue Laton)",
    displayOrder: 7,
  },
  {
    name: "Labour Charges – Plant Room & Basin Equipments",
    description: "Installation of MEP equipment",
    category: "Labour",
    sectionCode: "A",
    unit: "Lsm",
    warranty: "N/A",
    defaultRate: 15000,
    specification: "Installation, testing and commissioning of plant room and basin equipment including filter, pump, and lights.",
    displayOrder: 8,
  },
  {
    name: "Control & Regulating Equipments",
    description: "Valves and control fittings",
    category: "Plumbing",
    sectionCode: "A",
    unit: "Set",
    warranty: "01 Years",
    defaultRate: 12000,
    specification: "Butterfly valves, non-return valves, and pressure gauges for filtration system control.",
    displayOrder: 9,
  },
  {
    name: "Filtration Room Electrical Work",
    description: "Internal wiring for plant room",
    category: "Electrical",
    sectionCode: "A",
    unit: "Lsm",
    warranty: "01 Years",
    defaultRate: 8500,
    specification: "Internal electrical wiring, conduit laying and connection for all plant room equipment.",
    displayOrder: 10,
  },
  {
    name: "Labour Charges – Plumbing Works",
    description: "Piping installation labor",
    category: "Labour",
    sectionCode: "A",
    unit: "Lsm",
    warranty: "N/A",
    defaultRate: 25000,
    specification: "Labor charges for laying pressure pipes from pool to plant room and internal plant room plumbing.",
    displayOrder: 11,
  },
  {
    name: "Plumbing Materials",
    description: "UPVC Pipes and Fittings",
    category: "Plumbing",
    sectionCode: "A",
    unit: "Lsm",
    warranty: "N/A",
    defaultRate: 22000,
    specification: "Agri Pressure Pipes 10kg/cm sq. with valves and fittings. (Make: Astral/Prince/Finolex)",
    displayOrder: 12,
  },
  {
    name: "Swimming Pool Ladder",
    description: "SS 304 4-Step Ladder",
    category: "Accessories",
    sectionCode: "A",
    unit: "Nos",
    warranty: "01 Years",
    defaultRate: 12500,
    specification: "Heavy Duty 4-Step Stainless Steel 304 Ladder with Easy Mount Legs. (Make: Blue Laton)",
    displayOrder: 13,
  },
  {
    name: "Standard Skimmer",
    description: "ABS Wall Skimmer",
    category: "Plumbing",
    sectionCode: "A",
    unit: "Nos",
    warranty: "N/A",
    defaultRate: 6500,
    specification: "Standard Wall Skimmer with basket and lid for surface cleaning. (Make: Blue Laton)",
    displayOrder: 14,
  },

  // Section B – Testing & Electrical
  {
    name: "Testing & Commissioning of the Pool",
    description: "Final testing and handover",
    category: "Labour",
    sectionCode: "B",
    unit: "Lsm",
    warranty: "N/A",
    defaultRate: 5000,
    specification: "Final pressure testing, water balancing, and commissioning of the entire filtration system.",
    displayOrder: 15,
  },
  {
    name: "Transformer for Pool Lights",
    description: "12V AC Step-down Transformer",
    category: "Electrical",
    sectionCode: "B",
    unit: "Nos",
    warranty: "01 Years",
    defaultRate: 4500,
    specification: "12V AC step-down transformer for pool lights, weatherproof housing.",
    displayOrder: 16,
  },
  {
    name: "Electrical Materials",
    description: "Cables and conduits",
    category: "Electrical",
    sectionCode: "B",
    unit: "Lsm",
    warranty: "N/A",
    defaultRate: 12000,
    specification: "Copper cables, PVC conduits and accessories for pool and plant room electrical works.",
    displayOrder: 17,
  },
  {
    name: "Labour Charges – Pool Electrical Works",
    description: "Electrical installation labor",
    category: "Labour",
    sectionCode: "B",
    unit: "Lsm",
    warranty: "N/A",
    defaultRate: 7500,
    specification: "Labor for installation of control panel, lights connection, and cable laying.",
    displayOrder: 18,
  },
  {
    name: "Pool Starter for Pumps & Lights",
    description: "Manual Starter Box",
    category: "Electrical",
    sectionCode: "B",
    unit: "Nos",
    warranty: "01 Years",
    defaultRate: 3500,
    specification: "DOL Starter for 1.5HP pump with MCB protection for lights.",
    displayOrder: 19,
  },
  {
    name: "Electrical Control Panel with Timer",
    description: "Automatic Control Panel",
    category: "Electrical",
    sectionCode: "B",
    unit: "Nos",
    warranty: "01 Years",
    defaultRate: 15000,
    specification: "Stator Panel outdoor type double door wall mounted for 2HP pump with DC control space and timer for automatic operation. (Make: Blue Laton)",
    displayOrder: 20,
  },

  // Section C – Civil & Finishes
  {
    name: "Civil Work – Basin Construction",
    description: "RCC Basin Construction",
    category: "Civil",
    sectionCode: "C",
    unit: "Lsm",
    warranty: "10 Years",
    defaultRate: 450000,
    specification: "Construction of RCC basin as per structural design, including excavation, PCC, and RCC works.",
    displayOrder: 21,
  },

  // Section D – Maintenance Cleaning Kit
  {
    name: "Vacuum Head",
    description: "Weighted Floor Vacuum Head",
    category: "Maintenance",
    sectionCode: "D",
    unit: "Nos",
    warranty: "N/A",
    defaultRate: 4200,
    specification: "Flexible weighted Vacuum Head (14\"/18\") with wheels for floor cleaning. (Make: Blue Laton)\nMAKE : AQVASTAR- Singapore, HORNER Xpress Aquatix - US",
    displayOrder: 22,
  },
  {
    name: "Vacuum Hose",
    description: "Flexible Suction Hose",
    category: "Maintenance",
    sectionCode: "D",
    unit: "Nos",
    warranty: "N/A",
    defaultRate: 5500,
    specification: "1.5\" Heavy duty spiral wound suction hose, flexible EVA material. (Make: Blue Laton)\nMAKE : AQVASTAR- Singapore, HORNER Xpress Aquatix - US",
    displayOrder: 23,
  },
  {
    name: "Telescopic Rod",
    description: "Expandable Aluminum Pole",
    category: "Maintenance",
    sectionCode: "D",
    unit: "Nos",
    warranty: "N/A",
    defaultRate: 2800,
    specification: "Reinforced Aluminum Telescopic Rod (8-16 ft) for pool cleaning accessories.",
    displayOrder: 24,
  },
  {
    name: "Deep Leaf Rake",
    description: "Heavy Duty Leaf Net",
    category: "Maintenance",
    sectionCode: "D",
    unit: "Nos",
    warranty: "N/A",
    defaultRate: 1500,
    specification: "Heavy duty plastic frame with deep nylon mesh for leaf and debris collection.",
    displayOrder: 25,
  },
  {
    name: "Pool Chemicals",
    description: "Initial Chemical Kit",
    category: "Maintenance",
    sectionCode: "D",
    unit: "Lsm",
    warranty: "N/A",
    defaultRate: 8500,
    specification: "TCCA 90 Chlorine granules, Algaecide, and PH adjusters for initial water treatment.",
    displayOrder: 26,
  },
  {
    name: "Water Test Kit",
    description: "PH and Chlorine Test Kit",
    category: "Maintenance",
    sectionCode: "D",
    unit: "Nos",
    warranty: "N/A",
    defaultRate: 1500,
    specification: "Test Kit for measuring Chlorine & pH Levels in pool water. (Make: Emaux/Aqua)",
    displayOrder: 27,
  },
  {
    name: "Pool Brush",
    description: "Nylon Algae Brush",
    category: "Maintenance",
    sectionCode: "D",
    unit: "Nos",
    warranty: "N/A",
    defaultRate: 1200,
    specification: "18\" Nylon Bristle brush for wall and floor scrubbing.",
    displayOrder: 28,
  },

  // Part 2 – Pool Finishes
  {
    name: "Waterproofing",
    description: "Cementitious Waterproofing",
    category: "Finishes",
    sectionCode: "Part 2",
    unit: "Sft",
    warranty: "05 Years",
    defaultRate: 80,
    specification: "2-coat polymer-modified cementitious coating for pool basin.\nMAKE : AQVASTAR- Singapore, HORNER Xpress Aquatix - US",
    displayOrder: 29,
  },
  {
    name: "Coping Stone Labour Charges",
    description: "Labor for coping stone fixing",
    category: "Labour",
    sectionCode: "Part 2",
    unit: "Rft",
    warranty: "N/A",
    defaultRate: 150,
    specification: "Fixing charges for natural stone or RCC coping along the pool perimeter.",
    displayOrder: 30,
  },
  {
    name: "Swimming Pool Tiles",
    description: "Glass Mosaic / Ceramic Tiles",
    category: "Finishes",
    sectionCode: "Part 2",
    unit: "Sft",
    warranty: "N/A",
    defaultRate: 120,
    specification: "Ceramic or Glass Mosaic pool tiles, 1x1 or 2x2 inch.\nMAKE : AQVASTAR- Singapore, HORNER Xpress Aquatix - US",
    displayOrder: 31,
  },
  {
    name: "Tile Fixing & Epoxy Grouting Labour",
    description: "Labor for tile installation",
    category: "Labour",
    sectionCode: "Part 2",
    unit: "Sft",
    warranty: "N/A",
    defaultRate: 110,
    specification: "Labor charges for tile fixing with adhesive and epoxy grouting.",
    displayOrder: 32,
  },
];

export async function seedProducts() {
  console.log("Seeding products...");
  for (const p of products) {
    await prisma.product.upsert({
      where: { id: `seed-prod-${p.displayOrder}` }, // Using stable ID for idempotency or find by name
      update: {
        description: p.description,
        category: p.category,
        sectionCode: p.sectionCode,
        unit: p.unit,
        warranty: p.warranty,
        defaultRate: p.defaultRate,
        specification: p.specification,
        displayOrder: p.displayOrder,
      },
      create: {
        id: `seed-prod-${p.displayOrder}`,
        name: p.name,
        description: p.description,
        category: p.category,
        sectionCode: p.sectionCode,
        unit: p.unit,
        warranty: p.warranty,
        defaultRate: p.defaultRate,
        specification: p.specification,
        displayOrder: p.displayOrder,
      },
    });
  }
  console.log(`Seeded ${products.length} products.`);
}

if (require.main === module) {
  seedProducts()
    .then(() => prisma.$disconnect())
    .catch((e) => {
      console.error(e);
      prisma.$disconnect();
      process.exit(1);
    });
}
