import { PrismaClient } from "../generated/prisma-client";

const prisma = new PrismaClient();

export async function seedProducts() {
  console.log("Seeding template-driven products...");

  const products = [
    {
      id: "seed-temp-prod-1",
      name: "SWIMMING POOL FILTER",
      description: "",
      category: "PLANT ROOM EQUIPMENTS",
      sectionCode: "A",
      defaultRate: 48372,
      unit: "Nos",
      warranty: "01 Years for Filter Shell",
      templateText: "SWIMMING POOL FILTER:\n\nProviding supply of Bobbin Wound Sand Filter {{filterDiameter}} mm Dia fitted with pressure gauge panel, manual air bleeder, UV resistance surface, Non corrosive material, water drain and emptying plug fitted with collector arms and diffuser made from PVC and polypropylene.\n\nMAKE : AQVASTAR- Singapore, HORNER Xpress Aquatix - US",
      templateVariables: ["filterDiameter"],
      imagePath: "/template-images/mr-swimming-pools/swimming-pool-filter.png",
      sortOrder: 1,
    },
    {
      id: "seed-temp-prod-2",
      name: "FILTER MEDIA",
      description: "",
      category: "PLANT ROOM EQUIPMENTS",
      sectionCode: "A",
      defaultRate: 25,
      unit: "Kg",
      warranty: "N/A",
      templateText: "FILTER MEDIA:\n\nSupply of Silica sand media for the filtrations bed and testing and commissioning.\n\nSand & Gravel grading : {{sandGrading}}\n\nMAKE : RPSP",
      templateVariables: ["sandGrading"],
      imagePath: "/template-images/mr-swimming-pools/filter-media.png",
      sortOrder: 2,
    },
    {
      id: "seed-temp-prod-3",
      name: "06 WAY MULTIPORT VALVE",
      description: "",
      category: "PLANT ROOM EQUIPMENTS",
      sectionCode: "A",
      defaultRate: 12400,
      unit: "Nos",
      warranty: "01 Years",
      templateText: "06 WAY MULTIPORT VALVE {{valveSize}}:\n\nSupply of 6 way Multiport valve for the filter unit with pressure gauge, connectors & unions etc.\n\nType : Top Mounted.\n\nMAKE : AQVASTAR- Singapore, HORNER Xpress Aquatix - US",
      templateVariables: ["valveSize"],
      imagePath: "/template-images/mr-swimming-pools/06-way-multiport-valve.png",
      sortOrder: 3,
    },
    {
      id: "seed-temp-prod-4",
      name: "RECIRCULATING PUMP",
      description: "",
      category: "PLANT ROOM EQUIPMENTS",
      sectionCode: "A",
      defaultRate: 35145,
      unit: "Nos",
      warranty: "01 Years",
      templateText: "RECIRCULATING PUMP:\n\nSupply of {{pumpHP}} hp Three phase Self priming low noise pump with built in pre filter and removable strainer, and unions, Heat and chemical resistant casing with Noryl impeller & diffuser, Mechanical Seal, Class F insulation, IP 55 Protection etc.\n\nMAKE : AQVASTAR- Singapore, HORNER Xpress Aquatix - US",
      templateVariables: ["pumpHP"],
      imagePath: "/template-images/mr-swimming-pools/recirculating-pump.png",
      sortOrder: 4,
    },
    {
      id: "seed-temp-prod-5",
      name: "POOL MAIN DRAIN",
      description: "",
      category: "PLANT ROOM EQUIPMENTS",
      sectionCode: "A",
      defaultRate: 1900,
      unit: "Nos",
      warranty: "02 Years",
      templateText: "POOL MAIN DRAIN:\n\nSupply of {{mainDrainDiameter}} mm dia ABS made floor drain with {{mainDrainPipeSize}} pipe size for the pool water dewatering.\n\nMAKE : PENTAIR / MIDAS / AQUATIX / AQVASTAR",
      templateVariables: ["mainDrainDiameter", "mainDrainPipeSize"],
      imagePath: "/template-images/mr-swimming-pools/pool-main-drain.png",
      sortOrder: 5,
    },
    {
      id: "seed-temp-prod-6",
      name: "WALL INLETS",
      description: "",
      category: "PLANT ROOM EQUIPMENTS",
      sectionCode: "A",
      defaultRate: 920,
      unit: "Nos",
      warranty: "02 Years",
      templateText: "WALL INLETS:\n\nSupply of Wall / Floor inlets to the pool with {{wallInletPipeSize}} pipe connection & capable of discharging 5000 - 7000 liter / Hr.\n\nMAKE : PENTAIR / MIDAS / AQUATIX / AQVASTAR",
      templateVariables: ["wallInletPipeSize"],
      imagePath: "/template-images/mr-swimming-pools/wall-inlets-composite.png",
      sortOrder: 6,
    },
    {
      id: "seed-temp-prod-7",
      name: "SWIMMING POOL LADDER",
      description: "",
      category: "PLANT ROOM EQUIPMENTS",
      sectionCode: "A",
      defaultRate: 22500,
      unit: "Nos",
      warranty: "02 Years",
      templateText: "SWIMMING POOL LADDER:\n\nSupply of SS 304 Grade imported Swimming Pool ladder with necessary anchoring etc.\n\nNo of Steps : {{ladderSteps}}\n\nMAKE : PENTAIR / MIDAS / AQUATIX / AQVASTAR",
      templateVariables: ["ladderSteps"],
      imagePath: "/template-images/mr-swimming-pools/swimming-pool-ladder.png",
      sortOrder: 7,
    },
    {
      id: "seed-temp-prod-8",
      name: "STD SKIMMER",
      description: "",
      category: "PLANT ROOM EQUIPMENTS",
      sectionCode: "A",
      defaultRate: 6500,
      unit: "Nos",
      warranty: "01 Years",
      templateText: "STD SKIMMER:\n\nSupply of Standard SKIMMER fitted on the wall of the pool.\n\nMAKE : PENTAIR / MIDAS / AQUATIX / AQVASTAR",
      templateVariables: [],
      imagePath: "/template-images/mr-swimming-pools/std-skimmer.png",
      sortOrder: 8,
    },
    {
      id: "seed-temp-prod-9",
      name: "LABOUR CHARGES - PLANT ROOM & BASIN EQUIPMENTS",
      description: "",
      category: "PLANT ROOM EQUIPMENTS",
      sectionCode: "A",
      defaultRate: 25000,
      unit: "Lsm",
      warranty: "01 Years",
      templateText: "LABOUR CHARGES - PLANT ROOM & BASIN EQUIPMENTS:\n\nInstallation charges for Plant room filtration equipments & pool inside and outside basin fittings etc.",
      templateVariables: [],
      imagePath: "/template-images/mr-swimming-pools/labour-charges--plant-room-and-basin-equipments.png",
      sortOrder: 9,
    },
    {
      id: "seed-temp-prod-10",
      name: "PLUMBING MATERIALS",
      description: "",
      category: "PLANT ROOM EQUIPMENTS",
      sectionCode: "A",
      defaultRate: 115000,
      unit: "Lsm",
      warranty: "0",
      templateText: "PLUMBING MATERIALS:\n\nSupply of required Heavy duty 10kg/6kg {{plumbingPipeSize}} PVC/UPVC pipes with required fittings for the Pool and filtration room between plumbing connections etc. All in pasting type.\n\nUPVC Pipes - Elbows - Tees - Shoes\nEnd Cap - MTA - FTA - Coupling - UPVC Solvent etc.\n\nSCH-40 UPVC pipe or 10 Kgf/cm² PVC Pipe.\n\nMAKE : ASTRAL, SUPREME, FINOLEX etc.",
      templateVariables: ["plumbingPipeSize"],
      imagePath: "/template-images/mr-swimming-pools/plumbing-materials.png",
      sortOrder: 10,
    },
    {
      id: "seed-temp-prod-11",
      name: "CONTROL & REGULATING EQUIPMENTS",
      description: "",
      category: "PLANT ROOM EQUIPMENTS",
      sectionCode: "A",
      defaultRate: 3800,
      unit: "Nos",
      warranty: "01 Years",
      templateText: "CONTROL & REGULATING EQUIPMENTS:\n\nProviding Supply of Imported Ball valves & NRV to the Pump & filter and Standard ball valves to the Connection Pipe Lines etc.\n\nMAKE : CEPEX - Spain or Equivalent.",
      templateVariables: [],
      imagePath: "/template-images/mr-swimming-pools/control-regulating-equipments-composite.png",
      sortOrder: 11,
    },
    {
      id: "seed-temp-prod-12",
      name: "LABOUR CHARGES - PLUMBING WORKS",
      description: "",
      category: "PLANT ROOM EQUIPMENTS",
      sectionCode: "A",
      defaultRate: 25000,
      unit: "Lsm",
      warranty: "01 Years",
      templateText: "LABOUR CHARGES - PLUMBING WORKS:\n\nInstallation charges for Plant room filtration equipments & pool inside and outside basin fittings etc.\n\nMAKE :",
      templateVariables: [],
      imagePath: "/template-images/mr-swimming-pools/labour-plumbing.png",
      sortOrder: 12,
    },
    {
      id: "seed-temp-prod-13",
      name: "UNDERWATER LIGHT",
      description: "",
      category: "PLANT ROOM EQUIPMENTS",
      sectionCode: "A",
      defaultRate: 5800,
      unit: "Nos",
      warranty: "02 Years",
      templateText: "UNDERWATER LIGHT:\n\nProviding & Laying of {{underwaterLightWattage}} LED underwater Lights with IP68 ratings.",
      templateVariables: ["underwaterLightWattage"],
      imagePath: "/template-images/mr-swimming-pools/underwater-light.png",
      sortOrder: 13,
    },
    {
      id: "seed-temp-prod-14",
      name: "ELECTRICAL MATERIALS",
      description: "",
      category: "ELECTRICAL WORK",
      sectionCode: "B",
      defaultRate: 15000,
      unit: "Lsm",
      warranty: "0",
      templateText: "ELECTRICAL MATERIALS:\n\nSupply of 1.5 Sqmm x 2 core Electrical cabling with required conduits for Pool pumps to the electrical panels with required clamping etc.\n\nMAKE : V Guard, Finolex, Havells, Polycab Etc.",
      templateVariables: [],
      imagePath: "/template-images/mr-swimming-pools/electrical-materials-composite.png",
      sortOrder: 14,
    },
    {
      id: "seed-temp-prod-15",
      name: "LABOUR CHARGES - POOL ELECTRICAL WORKS",
      description: "",
      category: "ELECTRICAL WORK",
      sectionCode: "B",
      defaultRate: 20000,
      unit: "Lsm",
      warranty: "01 Years",
      templateText: "LABOUR CHARGES - POOL ELECTRICAL WORKS:\n\nLabour charges for Installation of Electrical cabling with required conduits for to Electrical Panel & Pool pumps to the electrical panels with required clamping etc.\n\nMAKE : V Guard, Finolex, Havells, Polycab Etc.",
      templateVariables: [],
      imagePath: "/template-images/mr-swimming-pools/labour-charges--pool-electrical-works.png",
      sortOrder: 15,
    },
    {
      id: "seed-temp-prod-16",
      name: "POOL STARTER FOR PUMPS & LIGHTS",
      description: "",
      category: "CONTROL PANEL",
      sectionCode: "C",
      defaultRate: 3800,
      unit: "Lsm",
      warranty: "01 Years",
      templateText: "POOL STARTER FOR PUMPS & LIGHTS:\n\nSupply & fixing of Single Phase starter.",
      templateVariables: [],
      imagePath: "/template-images/mr-swimming-pools/pool-starter-for-pumps-and-lights.png",
      sortOrder: 16,
    },
    {
      id: "seed-temp-prod-17",
      name: "TRANSFORMER FOR POOL LIGHTS",
      description: "",
      category: "CONTROL PANEL",
      sectionCode: "C",
      defaultRate: 7500,
      unit: "Nos",
      warranty: "01 YEARS",
      templateText: "TRANSFORMER FOR POOL LIGHTS:\n\nAC TO DC CONVERTING 12V TRANSFORMER",
      templateVariables: [],
      imagePath: null,
      imageText: null,
      sortOrder: 17,
    },
    {
      id: "seed-temp-prod-18",
      name: "TESTING & COMMISSIONING OF THE POOL",
      description: "",
      category: "CONTROL PANEL",
      sectionCode: "C",
      defaultRate: 10000,
      unit: "Lsm",
      warranty: "0",
      templateText: "TESTING & COMMISSIONING OF THE POOL:\n\nAfter water filling testing, commissioning & running of the pool with required manpower and chemicals for a month time to ensure the proper running condition of the pool filtration system and the pool water clean & Neat.\n\nMAKE : RPSP",
      templateVariables: [],
      imagePath: "/template-images/mr-swimming-pools/testing-and-commissioning-of-the-pool.png",
      sortOrder: 18,
    },
    {
      id: "seed-temp-prod-19",
      name: "VACUUM HEAD",
      description: "",
      category: "CLEANING KIT",
      sectionCode: "D",
      defaultRate: 2800,
      unit: "Nos",
      warranty: "0",
      templateText: "VACUUM HEAD:\n\nSupply of Vacuum Head ABS body with 4 wheels and brush etc.\n\nMAKE : PENTAIR / AQUATIX.",
      templateVariables: [],
      imagePath: "/template-images/mr-swimming-pools/vacuum-head.png",
      sortOrder: 19,
    },
    {
      id: "seed-temp-prod-20",
      name: "VACUUM HOSE",
      description: "",
      category: "CLEANING KIT",
      sectionCode: "D",
      defaultRate: 3500,
      unit: "Nos",
      warranty: "0",
      templateText: "VACUUM HOSE:\n\nSupply of Vacuum Hose 9 Meter Length for the Pool Cleaning.\n\nMAKE : PENTAIR / AQUATIX.",
      templateVariables: [],
      imagePath: "/template-images/mr-swimming-pools/vacuum-hose.png",
      sortOrder: 20,
    },
    {
      id: "seed-temp-prod-21",
      name: "TELESCOPIC ROD",
      description: "",
      category: "CLEANING KIT",
      sectionCode: "D",
      defaultRate: 4200,
      unit: "Nos",
      warranty: "0",
      templateText: "TELESCOPIC ROD:\n\nSupply of Telescopic rod 9m length aluminium pole expandable type.\n\nMAKE : PENTAIR / AQUATIX.",
      templateVariables: [],
      imagePath: "/template-images/mr-swimming-pools/telescopic-rod.png",
      sortOrder: 21,
    },
    {
      id: "seed-temp-prod-22",
      name: "DEEP LEAF RAKE",
      description: "",
      category: "CLEANING KIT",
      sectionCode: "D",
      defaultRate: 1400,
      unit: "Nos",
      warranty: "0",
      templateText: "DEEP LEAF RAKE:\n\nSupply of Deep net for the pool cleaning.\n\nMAKE : PENTAIR / AQUATIX.",
      templateVariables: [],
      imagePath: "/template-images/mr-swimming-pools/deep-leaf-rake.png",
      sortOrder: 22,
    },
    {
      id: "seed-temp-prod-23",
      name: "WATER TEST KIT",
      description: "",
      category: "CLEANING KIT",
      sectionCode: "D",
      defaultRate: 700,
      unit: "Nos",
      warranty: "0",
      templateText: "WATER TEST KIT:\n\nSupply of Pool water Test Kit for pH and Chlorin.\n\nMAKE : PENTAIR / AQUATIX.",
      templateVariables: [],
      imagePath: "/template-images/mr-swimming-pools/water-test-kit.png",
      sortOrder: 23,
    },
    {
      id: "seed-temp-prod-24",
      name: "POOL BRUSH",
      description: "",
      category: "CLEANING KIT",
      sectionCode: "D",
      defaultRate: 1400,
      unit: "Nos",
      warranty: "0",
      templateText: "POOL BRUSH:\n\nSupply of Pool cleaning Brush with aluminium back.\n\nMAKE : PENTAIR / AQUATIX.",
      templateVariables: [],
      imagePath: "/template-images/mr-swimming-pools/pool-brush.png",
      sortOrder: 24,
    },
    {
      id: "seed-temp-prod-25",
      name: "POOL CHEMICALS",
      description: "",
      category: "CLEANING KIT",
      sectionCode: "D",
      defaultRate: 5000,
      unit: "Lsm",
      warranty: "0",
      templateText: "POOL CHEMICALS:\n\nSupply of Pool Chemicals like TCCA 90, Algaecide, pH Balancing Chemicals etc for initial Pool cleaning etc.",
      templateVariables: [],
      imagePath: "/template-images/mr-swimming-pools/pool-chemicals.png",
      sortOrder: 25,
    },
    {
      id: "seed-temp-prod-26",
      name: "WATER PROOFING",
      description: "",
      category: "POOL FINISHES",
      sectionCode: "Part 2",
      defaultRate: 65,
      unit: "Lsm",
      warranty: "05 Years",
      templateText: "WATER PROOFING:\n\nSupply and applying of ELESTO-MERICO Two coat weather proof high flexibility cementitious mortar with crack bridging capacity up to 2 mm, Edge band for all the corners & Brush bond of 2 coats for swimming pools, Balancing Tank, Filtration room & overflow Gutter.\n\nMAKE : NIPPON / MAPEI / KERAKOLL / NIPPON",
      templateVariables: [],
      imagePath: "/template-images/mr-swimming-pools/waterproofing.png",
      sortOrder: 26,
    },
    {
      id: "seed-temp-prod-27",
      name: "COPING STONE",
      description: "",
      category: "POOL FINISHES",
      sectionCode: "Part 2",
      defaultRate: 80,
      unit: "Sft",
      warranty: "0",
      templateText: "COPING STONE: LABOR CHARGES ONLY (**Excluding Granite/cement):\n\nLabor charges for fixing of 20mm thick Granite stone as coping stone with required sand, cement or Adhesive including transportation and unloading charges etc.\n\nMAKE : SADARAHALLI / BANGALORE STONE.",
      templateVariables: [],
      imagePath: "/template-images/mr-swimming-pools/coping-stone.png",
      sortOrder: 27,
    },
    {
      id: "seed-temp-prod-28",
      name: "SWIMMING POOL TILES",
      description: "",
      category: "POOL FINISHES",
      sectionCode: "Part 2",
      defaultRate: 90,
      unit: "Sft",
      warranty: "0",
      templateText: "SWIMMING POOL TILES:\n\nSupply of 20mm x 20mm size Glass Mosaic tiles standard colour for the floor and walls of the pool.\n\nMAKE : ",
      templateVariables: [],
      imagePath: "/template-images/mr-swimming-pools/swimming-pool-tiles.png",
      sortOrder: 28,
    },
    {
      id: "seed-temp-prod-29",
      name: "Labour charges for Tiles fixing & Epoxy Grouting",
      description: "",
      category: "POOL FINISHES",
      sectionCode: "Part 2",
      defaultRate: 110,
      unit: "Sft",
      warranty: "01 Year for Tiles Fixing",
      templateText: "Labour charges for Tiles fixing & Epoxy Grouting:\n\nSupply of required Tools and materials for cleaning after Grouting etc.",
      templateVariables: [],
      imagePath: null,
      imageText: "RPSP",
      sortOrder: 29,
    },
  ];

  for (const product of products) {
    await prisma.product.upsert({
      where: { id: product.id },
      update: product,
      create: product,
    });
  }

  console.log(`Seeded ${products.length} template products.`);
}

if (require.main === module) {
  seedProducts()
    .then(() => prisma.$disconnect())
    .catch((e) => {
      console.error(e);
      prisma.$disconnect();
      process.exit(1);
    });
}
