import { QuotationFormValues } from "@/types";

export const MR_MASTER_TEMPLATE: Partial<QuotationFormValues> = {
  gstPercent: 18,
  projectSpecifications: {
    poolLength: "30",
    poolWidth: "20",
    poolDepth: "5",
    poolVolume: "3000 Cft",
    plantRoomSize: "8'X8'X6'",
    shapeOfPool: "RECTANGLE POOL",
    typeOfPool: "SKIMMER TYPE",
    totalPoolVolume: "84951 Ltrs",
    filtrationVolume: "84951 Ltrs",
    turnoverPeriod: "4 Hours",
    tilingArea: "1100 Sft",
    copingArea: "100 Rft",
    waterproofingArea: "1100 Sft"
  },
  sections: [
    { code: "A", title: "PLANT ROOM EQUIPMENTS", included: true, sortOrder: 1 },
    { code: "B", title: "FILTRATION ROOM ELECTRICAL WORK", included: true, sortOrder: 2 },
    { code: "C", title: "ELECTRICAL CONTROL PANEL WITH TIMER", included: true, sortOrder: 3 },
    { code: "D", title: "SUPPLY OF SWIMMING POOL MAINTENANCE CLEANING KIT", included: true, sortOrder: 4 },
    { code: "Part 2", title: "Part2:POOL FINISHES", included: true, sortOrder: 5 }
  ],
  items: [
    // SECTION A – PLANT ROOM EQUIPMENTS
    {
      section: "A",
      serialNo: 1,
      category: "PLANT ROOM EQUIPMENTS",
      description: "SWIMMING POOL FILTER:\n\nProviding supply of Bobbin Wound Sand Filter {{filterDiameter}} mm Dia fitted with pressure gauge panel, manual air bleeder, UV resistance surface, Non corrosive material, water drain and emptying plug fitted with collector arms and diffuser made from PVC and polypropylene.\n\nMAKE : AQVASTAR- Singapore, HORNER Xpress Aquatix - US",
      warranty: "01 Years for Filter Shell",
      qty: 1,
      unit: "Nos",
      rate: 48372,
      amount: 48372,
      productId: "seed-temp-prod-1",
      variableValues: { "filterDiameter": "700" },
      imageUrl: "/template-images/mr-swimming-pools/swimming-pool-filter.png"
    },
    {
      section: "A",
      serialNo: 2,
      category: "PLANT ROOM EQUIPMENTS",
      description: "FILTER MEDIA:\n\nSupply of Silica sand media for the filtrations bed and testing and commissioning.\n\nSand & Gravel grading : {{sandGrading}}\n\nMAKE : RPSP",
      warranty: "N/A",
      qty: 250,
      unit: "Kg",
      rate: 25,
      amount: 6250,
      productId: "seed-temp-prod-2",
      variableValues: { "sandGrading": "0.2 - 1.0 mm & 2 - 3 mm" },
      imageUrl: "/template-images/mr-swimming-pools/filter-media.png"
    },
    {
      section: "A",
      serialNo: 3,
      category: "PLANT ROOM EQUIPMENTS",
      description: "06 WAY MULTIPORT VALVE {{valveSize}}:\n\nSupply of 6 way Multiport valve for the filter unit with pressure gauge, connectors & unions etc.\n\nType : Top Mounted.\n\nMAKE : AQVASTAR- Singapore, HORNER Xpress Aquatix - US",
      warranty: "01 Years",
      qty: 1,
      unit: "Nos",
      rate: 12400,
      amount: 12400,
      productId: "seed-temp-prod-3",
      variableValues: { "valveSize": "1.5\"" },
      imageUrl: "/template-images/mr-swimming-pools/06-way-multiport-valve.png"
    },
    {
      section: "A",
      serialNo: 4,
      category: "PLANT ROOM EQUIPMENTS",
      description: "RECIRCULATING PUMP:\n\nSupply of {{pumpHP}} hp Three phase Self priming low noise pump with built in pre filter and removable strainer, and unions, Heat and chemical resistant casing with Noryl impeller & diffuser, Mechanical Seal, Class F insulation, IP 55 Protection etc.\n\nMAKE : AQVASTAR- Singapore, HORNER Xpress Aquatix - US",
      warranty: "01 Years",
      qty: 2,
      unit: "Nos",
      rate: 35145,
      amount: 70290,
      productId: "seed-temp-prod-4",
      variableValues: { "pumpHP": "1" },
      imageUrl: "/template-images/mr-swimming-pools/recirculating-pump.png"
    },
    {
      section: "A",
      serialNo: 5,
      category: "PLANT ROOM EQUIPMENTS",
      description: "POOL MAIN DRAIN:\n\nSupply of {{mainDrainDiameter}} mm dia ABS made floor drain with {{mainDrainPipeSize}} pipe size for the pool water dewatering.\n\nMAKE : PENTAIR / MIDAS / AQUATIX / AQVASTAR",
      warranty: "02 Years",
      qty: 2,
      unit: "Nos",
      rate: 1900,
      amount: 3800,
      productId: "seed-temp-prod-5",
      variableValues: { "mainDrainDiameter": "200", "mainDrainPipeSize": "2\"" },
      imageUrl: "/template-images/mr-swimming-pools/pool-main-drain.png"
    },
    {
      section: "A",
      serialNo: 6,
      category: "PLANT ROOM EQUIPMENTS",
      description: "WALL INLETS:\n\nSupply of Wall / Floor inlets to the pool with {{wallInletPipeSize}} pipe connection & capable of discharging 5000 - 7000 liter / Hr.\n\nMAKE : PENTAIR / MIDAS / AQUATIX / AQVASTAR",
      warranty: "02 Years",
      qty: 6,
      unit: "Nos",
      rate: 920,
      amount: 5520,
      productId: "seed-temp-prod-6",
      variableValues: { "wallInletPipeSize": "2\"" },
      imageUrl: "/template-images/mr-swimming-pools/wall-inlets-composite.png"
    },
    {
      section: "A",
      serialNo: 7,
      category: "PLANT ROOM EQUIPMENTS",
      description: "SWIMMING POOL LADDER:\n\nSupply of SS 304 Grade imported Swimming Pool ladder with necessary anchoring etc.\n\nNo of Steps : {{ladderSteps}}\n\nMAKE : PENTAIR / MIDAS / AQUATIX / AQVASTAR",
      warranty: "02 Years",
      qty: 2,
      unit: "Nos",
      rate: 22500,
      amount: 45000,
      productId: "seed-temp-prod-7",
      variableValues: { "ladderSteps": "03 & 04" },
      imageUrl: "/template-images/mr-swimming-pools/swimming-pool-ladder.png"
    },
    {
      section: "A",
      serialNo: 8,
      category: "PLANT ROOM EQUIPMENTS",
      description: "STD SKIMMER:\n\nSupply of Standard SKIMMER fitted on the wall of the pool.\n\nMAKE : PENTAIR / MIDAS / AQUATIX / AQVASTAR",
      warranty: "01 Years",
      qty: 2,
      unit: "Nos",
      rate: 6500,
      amount: 13000,
      productId: "seed-temp-prod-8",
      imageUrl: "/template-images/mr-swimming-pools/std-skimmer.png",
      variableValues: {},
    },
    {
      section: "A",
      serialNo: 9,
      category: "PLANT ROOM EQUIPMENTS",
      description: "LABOUR CHARGES - PLANT ROOM & BASIN EQUIPMENTS:\n\nInstallation charges for Plant room filtration equipments & pool inside and outside basin fittings etc.",
      warranty: "01 Years",
      qty: 1,
      unit: "Lsm",
      rate: 25000,
      amount: 25000,
      productId: "seed-temp-prod-9",
      imageUrl: "/template-images/mr-swimming-pools/labour-charges--plant-room-and-basin-equipments.png",
      variableValues: {},
    },
    {
      section: "A",
      serialNo: 10,
      category: "PLANT ROOM EQUIPMENTS",
      description: "PLUMBING MATERIALS:\n\nSupply of required Heavy duty 10kg/6kg {{plumbingPipeSize}} PVC/UPVC pipes with required fittings for the Pool and filtration room between plumbing connections etc. All in pasting type.\n\nUPVC Pipes - Elbows - Tees - Shoes\nEnd Cap - MTA - FTA - Coupling - UPVC Solvent etc.\n\nSCH-40 UPVC pipe or 10 Kgf/cm² PVC Pipe.\n\nMAKE : ASTRAL, SUPREME, FINOLEX etc.",
      warranty: "0",
      qty: 1,
      unit: "Lsm",
      rate: 115000,
      amount: 115000,
      productId: "seed-temp-prod-10",
      imageUrl: "/template-images/mr-swimming-pools/plumbing-materials.png",
      variableValues: { "plumbingPipeSize": "1 1/2\"" },
    },
    {
      section: "A",
      serialNo: 11,
      category: "PLANT ROOM EQUIPMENTS",
      description: "CONTROL & REGULATING EQUIPMENTS:\n\nProviding Supply of Imported Ball valves & NRV to the Pump & filter and Standard ball valves to the Connection Pipe Lines etc.\n\nMAKE : CEPEX - Spain or Equivalent.",
      warranty: "01 Years",
      qty: 18,
      unit: "Nos",
      rate: 3800,
      amount: 68400,
      productId: "seed-temp-prod-11",
      imageUrl: "/template-images/mr-swimming-pools/control-regulating-equipments-composite.png",
      variableValues: {},
    },
    {
      section: "A",
      serialNo: 12,
      category: "PLANT ROOM EQUIPMENTS",
      description: "LABOUR CHARGES - PLUMBING WORKS:\n\nInstallation charges for Plant room filtration equipments & pool inside and outside basin fittings etc.\n\nMAKE :",
      warranty: "01 Years",
      qty: 1,
      unit: "Lsm",
      rate: 25000,
      amount: 25000,
      productId: "seed-temp-prod-12",
      imageUrl: "/template-images/mr-swimming-pools/labour-plumbing.png",
      variableValues: {},
    },
    {
      section: "A",
      serialNo: 13,
      category: "PLANT ROOM EQUIPMENTS",
      description: "UNDERWATER LIGHT:\n\nProviding & Laying of {{underwaterLightWattage}} LED underwater Lights with IP68 ratings.",
      warranty: "02 Years",
      qty: 6,
      unit: "Nos",
      rate: 5800,
      amount: 34800,
      productId: "seed-temp-prod-13",
      variableValues: { "underwaterLightWattage": "24w/18v" },
      imageUrl: "/template-images/mr-swimming-pools/underwater-light.png"
    },

    // SECTION B – FILTRATION ROOM ELECTRICAL WORK
    {
      section: "B",
      serialNo: 1,
      category: "ELECTRICAL WORK",
      description: "ELECTRICAL MATERIALS:\n\nSupply of 1.5 Sqmm x 2 core Electrical cabling with required conduits for Pool pumps to the electrical panels with required clamping etc.\n\nMAKE : V Guard, Finolex, Havells, Polycab Etc.",
      warranty: "0",
      qty: 1,
      unit: "Lsm",
      rate: 15000,
      amount: 15000,
      productId: "seed-temp-prod-14",
      imageUrl: "/template-images/mr-swimming-pools/electrical-materials-composite.png",
    },
    {
      section: "B",
      serialNo: 2,
      category: "ELECTRICAL WORK",
      description: "LABOUR CHARGES - POOL ELECTRICAL WORKS:\n\nLabour charges for Installation of Electrical cabling with required conduits for to Electrical Panel & Pool pumps to the electrical panels with required clamping etc.\n\nMAKE : V Guard, Finolex, Havells, Polycab Etc.",
      warranty: "01 Years",
      qty: 1,
      unit: "Lsm",
      rate: 20000,
      amount: 20000,
      productId: "seed-temp-prod-15",
      imageUrl: "/template-images/mr-swimming-pools/labour-charges--pool-electrical-works.png",
    },

    // SECTION C – ELECTRICAL CONTROL PANEL WITH TIMER
    {
      section: "C",
      serialNo: 1,
      category: "CONTROL PANEL",
      description: "POOL STARTER FOR PUMPS & LIGHTS:\n\nSupply & fixing of Single Phase starter.",
      warranty: "01 Years",
      qty: 2,
      unit: "Lsm",
      rate: 3800,
      amount: 7600,
      productId: "seed-temp-prod-16",
      imageUrl: "/template-images/mr-swimming-pools/pool-starter-for-pumps-and-lights.png",
    },
    {
      section: "C",
      serialNo: 2,
      category: "CONTROL PANEL",
      description: "TRANSFORMER FOR POOL LIGHTS:\n\nAC TO DC CONVERTING 12V TRANSFORMER",
      warranty: "01 YEARS",
      qty: 1,
      unit: "Nos",
      rate: 7500,
      amount: 7500,
      productId: "seed-temp-prod-17",
      imageUrl: null,
      imageText: null,
    },
    {
      section: "C",
      serialNo: 3,
      category: "CONTROL PANEL",
      description: "TESTING & COMMISSIONING OF THE POOL:\n\nAfter water filling testing, commissioning & running of the pool with required manpower and chemicals for a month time to ensure the proper running condition of the pool filtration system and the pool water clean & Neat.\n\nMAKE : RPSP",
      warranty: "0",
      qty: 1,
      unit: "Lsm",
      rate: 10000,
      amount: 10000,
      productId: "seed-temp-prod-18",
      imageUrl: "/template-images/mr-swimming-pools/testing-and-commissioning-of-the-pool.png",
    },

    // SECTION D – SUPPLY OF SWIMMING POOL MAINTENANCE CLEANING KIT
    {
      section: "D",
      serialNo: 1,
      category: "CLEANING KIT",
      description: "VACUUM HEAD:\n\nSupply of Vacuum Head ABS body with 4 wheels and brush etc.\n\nMAKE : PENTAIR / AQUATIX.",
      warranty: "0",
      qty: 1,
      unit: "Nos",
      rate: 2800,
      amount: 2800,
      productId: "seed-temp-prod-19",
      imageUrl: "/template-images/mr-swimming-pools/vacuum-head.png"
    },
    {
      section: "D",
      serialNo: 2,
      category: "CLEANING KIT",
      description: "VACUUM HOSE:\n\nSupply of Vacuum Hose 9 Meter Length for the Pool Cleaning.\n\nMAKE : PENTAIR / AQUATIX.",
      warranty: "0",
      qty: 1,
      unit: "Nos",
      rate: 3500,
      amount: 3500,
      productId: "seed-temp-prod-20",
      imageUrl: "/template-images/mr-swimming-pools/vacuum-hose.png"
    },
    {
      section: "D",
      serialNo: 3,
      category: "CLEANING KIT",
      description: "TELESCOPIC ROD:\n\nSupply of Telescopic rod 9m length aluminium pole expandable type.\n\nMAKE : PENTAIR / AQUATIX.",
      warranty: "0",
      qty: 1,
      unit: "Nos",
      rate: 4200,
      amount: 4200,
      productId: "seed-temp-prod-21",
      imageUrl: "/template-images/mr-swimming-pools/telescopic-rod.png"
    },
    {
      section: "D",
      serialNo: 4,
      category: "CLEANING KIT",
      description: "DEEP LEAF RAKE:\n\nSupply of Deep net for the pool cleaning.\n\nMAKE : PENTAIR / AQUATIX.",
      warranty: "0",
      qty: 1,
      unit: "Nos",
      rate: 1400,
      amount: 1400,
      productId: "seed-temp-prod-22",
      imageUrl: "/template-images/mr-swimming-pools/deep-leaf-rake.png"
    },
    {
      section: "D",
      serialNo: 5,
      category: "CLEANING KIT",
      description: "WATER TEST KIT:\n\nSupply of Pool water Test Kit for pH and Chlorin.\n\nMAKE : PENTAIR / AQUATIX.",
      warranty: "0",
      qty: 1,
      unit: "Nos",
      rate: 700,
      amount: 700,
      productId: "seed-temp-prod-23",
      imageUrl: "/template-images/mr-swimming-pools/water-test-kit.png"
    },
    {
      section: "D",
      serialNo: 24,
      category: "CLEANING KIT",
      description: "POOL BRUSH:\n\nSupply of Pool cleaning Brush with aluminium back.\n\nMAKE : PENTAIR / AQUATIX.",
      warranty: "0",
      qty: 1,
      unit: "Nos",
      rate: 1400,
      amount: 1400,
      productId: "seed-temp-prod-24",
      imageUrl: "/template-images/mr-swimming-pools/pool-brush.png"
    },
    {
      section: "D",
      serialNo: 25,
      category: "CLEANING KIT",
      description: "POOL CHEMICALS:\n\nSupply of Pool Chemicals like TCCA 90, Algaecide, pH Balancing Chemicals etc for initial Pool cleaning etc.",
      warranty: "0",
      qty: 1,
      unit: "Lsm",
      rate: 5000,
      amount: 5000,
      productId: "seed-temp-prod-25",
      imageUrl: "/template-images/mr-swimming-pools/pool-chemicals.png"
    },

    // PART 2 – POOL FINISHES
    {
      section: "Part 2",
      serialNo: 1,
      category: "POOL FINISHES",
      description: "WATER PROOFING:\n\nSupply and applying of ELESTO-MERICO Two coat weather proof high flexibility cementitious mortar with crack bridging capacity up to 2 mm, Edge band for all the corners & Brush bond of 2 coats for swimming pools, Balancing Tank, Filtration room & overflow Gutter.\n\nMAKE : NIPPON / MAPEI / KERAKOLL / NIPPON",
      warranty: "05 Years",
      qty: 1420,
      unit: "Lsm",
      rate: 65,
      amount: 92300,
      productId: "seed-temp-prod-26",
      imageUrl: "/template-images/mr-swimming-pools/waterproofing.png",
    },
    {
      section: "Part 2",
      serialNo: 2,
      category: "POOL FINISHES",
      description: "COPING STONE: LABOR CHARGES ONLY (**Excluding Granite/cement):\n\nLabor charges for fixing of 20mm thick Granite stone as coping stone with required sand, cement or Adhesive including transportation and unloading charges etc.\n\nMAKE : SADARAHALLI / BANGALORE STONE.",
      warranty: "0",
      qty: 104,
      unit: "Sft",
      rate: 80,
      amount: 8320,
      productId: "seed-temp-prod-27",
      imageUrl: "/template-images/mr-swimming-pools/coping-stone.png",
    },
    {
      section: "Part 2",
      serialNo: 3,
      category: "POOL FINISHES",
      description: "SWIMMING POOL TILES:\n\nSupply of 20mm x 20mm size Glass Mosaic tiles standard colour for the floor and walls of the pool.\n\nMAKE : ",
      warranty: "0",
      qty: 1100,
      unit: "Sft",
      rate: 90,
      amount: 99000,
      productId: "seed-temp-prod-28",
      imageUrl: "/template-images/mr-swimming-pools/swimming-pool-tiles.png",
    },
    {
      section: "Part 2",
      serialNo: 4,
      category: "POOL FINISHES",
      description: "Labour charges for Tiles fixing & Epoxy Grouting:\n\nSupply of required Tools and materials for cleaning after Grouting etc.",
      warranty: "01 Year for Tiles Fixing",
      qty: 1100,
      unit: "Sft",
      rate: 110,
      amount: 121000,
      productId: "seed-temp-prod-29",
      imageUrl: null,
      imageText: "RPSP",
    }
  ],
  terms: `1. Single phase connection up to the plant room is in your scope of work.
2. Back wash line after the plant room and water supply to balance tank is in your scope.
3. All Civil works mentioned above are at our scope.
4. Rates are valid for 30 days from the date of quotation.`,
  paymentTerms: `1. 30% Payment along with the PO.
2. 30% payment after bar bending.
3. 30% during tile fixing work.
4. 10% on successful commissioning and testing.`,
  notes: ""
};
