import type { PoolTypeFilter } from "@/types";

export type MRProductDefinition = {
  id: string;
  name: string;
  title: string;
  section: string;
  category: string;
  serialNo: number;
  defaultQty: number;
  defaultRate: number;
  unit: string;
  warranty: string;
  /** Template body (variables as {{name}}). Title is stored separately. */
  description: string;
  templateVariables?: string[];
  defaultVariableValues?: Record<string, string>;
  imagePath: string | null;
  imageText?: string | null;
  poolTypeFilter?: PoolTypeFilter;
  sortOrder: number;
};

/** Canonical MR Swimming Pools products — aligned with reference overflow quotation PDF (Jun 2026). */
export const MR_PRODUCT_DEFINITIONS: MRProductDefinition[] = [
  {
    id: "seed-temp-prod-1",
    name: "SWIMMING POOL FILTER",
    title: "SWIMMING POOL FILTER",
    section: "A",
    category: "PLANT ROOM EQUIPMENTS",
    serialNo: 1,
    defaultQty: 1,
    defaultRate: 78700,
    unit: "Nos",
    warranty: "01 Years for Filter Shell",
    description:
      'Providing supply of Bobbin Wound Sand Filter {{filterDiameter}} mm Dia fitted with pressure gauge panel, manual air bleeder, UV resistance surface, Non corrosive material, water drain and emptying plug fitted with collector arms and diffuser made from PVC and polypropylene.\n\nDesign Flow rate : {{designFlowRate}}\nMaximum working pressure : {{maxPressure}}\n\nMAKE : AQVASTAR- Singapore, HORNER Xpress Aquatix - US',
    templateVariables: ["filterDiameter", "designFlowRate", "maxPressure"],
    defaultVariableValues: { filterDiameter: "900", designFlowRate: "25 m3/h", maxPressure: "3.5 Bar" },
    imagePath: "/template-images/mr-swimming-pools/swimming-pool-filter.png",
    sortOrder: 1,
  },
  {
    id: "seed-temp-prod-2",
    name: "FILTER MEDIA",
    title: "FILTER MEDIA",
    section: "A",
    category: "PLANT ROOM EQUIPMENTS",
    serialNo: 2,
    defaultQty: 450,
    defaultRate: 25,
    unit: "Kg",
    warranty: "N/A",
    description:
      "Supply of Silica sand media for the filtrations bed and testing and commissioning.\n\nSand & Gravel grading : {{sandGrading}}\n\nMAKE : RPSP",
    templateVariables: ["sandGrading"],
    defaultVariableValues: { sandGrading: "0.2 - 1.0 mm & 2 - 3mm" },
    imagePath: "/template-images/mr-swimming-pools/filter-media.png",
    sortOrder: 2,
  },
  {
    id: "seed-temp-prod-3",
    name: "06 WAY MULTIPORT VALVE",
    title: "06 WAY MULTIPORT VALVE",
    section: "A",
    category: "PLANT ROOM EQUIPMENTS",
    serialNo: 3,
    defaultQty: 1,
    defaultRate: 12500,
    unit: "Nos",
    warranty: "01 Years",
    description:
      'Supply of 6 way Multiport valve for the filter unit with Pressure gauge, connectors & unions etc.\n\nType : Top Mounted.\n\nMAKE : PENTAIR / MIDAS / AQUATIX / AQVASTAR',
    templateVariables: ["valveSize"],
    defaultVariableValues: { valveSize: '2"' },
    imagePath: "/template-images/mr-swimming-pools/06-way-multiport-valve.png",
    sortOrder: 3,
  },
  {
    id: "seed-temp-prod-4",
    name: "RECIRCULATING PUMP",
    title: "RECIRCULATING PUMP",
    section: "A",
    category: "PLANT ROOM EQUIPMENTS",
    serialNo: 4,
    defaultQty: 2,
    defaultRate: 61000,
    unit: "Nos",
    warranty: "01 Years",
    description:
      "Supply of {{pumpHP}} hp Single phase Self priming low noise pump with built in Pre filter and removable strainer, and unions, Heat and chemical resistant casing with Noryle impeller & diffuser, Mechanical Seal, Class F insulation, IP 55 Protection etc.\n\nMAKE: HORNER EXPRESS/ AQUATIX / AQVASTAR",
    templateVariables: ["pumpHP"],
    defaultVariableValues: { pumpHP: "3" },
    imagePath: "/template-images/mr-swimming-pools/recirculating-pump.png",
    sortOrder: 4,
  },
  {
    id: "seed-temp-prod-5",
    name: "POOL MAIN DRAIN",
    title: "POOL MAIN DRAIN",
    section: "A",
    category: "PLANT ROOM EQUIPMENTS",
    serialNo: 5,
    defaultQty: 2,
    defaultRate: 2400,
    unit: "Nos",
    warranty: "02 Years",
    description:
      'Supply of {{mainDrainDiameter}} mm dia ABS made floor drain with {{mainDrainPipeSize}} pipe size for the pool water dewatering.\n\nMAKE: PENTAIR / MIDAS / AQUATIX / AQVASTAR',
    templateVariables: ["mainDrainDiameter", "mainDrainPipeSize"],
    defaultVariableValues: { mainDrainDiameter: "200", mainDrainPipeSize: '2"' },
    imagePath: "/template-images/mr-swimming-pools/pool-main-drain.png",
    sortOrder: 5,
  },
  {
    id: "seed-temp-prod-6",
    name: "FLOOR INLETS",
    title: "FLOOR INLETS",
    section: "A",
    category: "PLANT ROOM EQUIPMENTS",
    serialNo: 6,
    defaultQty: 9,
    defaultRate: 1120,
    unit: "Nos",
    warranty: "02 Years",
    description:
      'Supply of Wall / Floor inlets to the pool with {{wallInletPipeSize}} pipe connection & capable of discharging 5000 - 7000 liter / Hr.\n\nMAKE : PENTAIR / MIDAS / AQUATIX / AQVASTAR',
    templateVariables: ["wallInletPipeSize"],
    defaultVariableValues: { wallInletPipeSize: '2"' },
    imagePath: "/template-images/mr-swimming-pools/floor-inlets-composite.png",
    sortOrder: 6,
  },
  {
    id: "seed-temp-prod-7",
    name: "SWIMMING POOL LADDER",
    title: "SWIMMING POOL LADDER",
    section: "A",
    category: "PLANT ROOM EQUIPMENTS",
    serialNo: 7,
    defaultQty: 2,
    defaultRate: 550,
    unit: "Nos",
    warranty: "02 Years",
    description:
      "Supply of SS 304 Grade imported Swimming Pool ladder with necessary anchoring etc.\n\nNo of Steps : {{ladderSteps}}\n\nMAKE : PENTAIR / MIDAS / AQUATIX / AQVASTAR",
    templateVariables: ["ladderSteps"],
    defaultVariableValues: { ladderSteps: "04 & 03" },
    imagePath: "/template-images/mr-swimming-pools/swimming-pool-ladder.png",
    sortOrder: 7,
  },
  {
    id: "seed-temp-prod-30",
    name: "OVERFLOW GRATING",
    title: "OVERFLOW GRATING",
    section: "A",
    category: "PLANT ROOM EQUIPMENTS",
    serialNo: 8,
    defaultQty: 58,
    defaultRate: 1150,
    unit: "Rft",
    warranty: "01 Years",
    description:
      "Supply of Standard GRATINGS fitted on the gutter surrounding the Pool.\n\nMAKE : PENTAIR / MIDAS / AQUATIX / AQVASTAR",
    imagePath: "/template-images/mr-swimming-pools/overflow-grating.png",
    poolTypeFilter: "overflow",
    sortOrder: 8,
  },
  {
    id: "seed-temp-prod-31",
    name: "WALL CONDUITS",
    title: "WALL CONDUITS",
    section: "A",
    category: "PLANT ROOM EQUIPMENTS",
    serialNo: 9,
    defaultQty: 3,
    defaultRate: 22500,
    unit: "Nos",
    warranty: "02 Years",
    description:
      'Supply of wall conduits to the pool for Wall Inlets & Vacuum Points with 2" pipe connection.\n\nMAKE : PENTAIR / MIDAS / AQUATIX / AQVASTAR',
    imagePath: "/template-images/mr-swimming-pools/wall-conduits.png",
    poolTypeFilter: "overflow",
    sortOrder: 9,
  },
  {
    id: "seed-temp-prod-32",
    name: "VACUUM POINT",
    title: "VACUUM POINT",
    section: "A",
    category: "PLANT ROOM EQUIPMENTS",
    serialNo: 10,
    defaultQty: 2,
    defaultRate: 900,
    unit: "Nos",
    warranty: "02 Years",
    description:
      "Supply of Standard Vacuum Point with threaded connection for cleaning the pool.\n\nMAKE : PENTAIR / MIDAS / AQUATIX / AQVASTAR",
    imagePath: "/template-images/mr-swimming-pools/vacuum-point.png",
    poolTypeFilter: "overflow",
    sortOrder: 10,
  },
  {
    id: "seed-temp-prod-8",
    name: "STD SKIMMER",
    title: "STD SKIMMER",
    section: "A",
    category: "PLANT ROOM EQUIPMENTS",
    serialNo: 11,
    defaultQty: 2,
    defaultRate: 6500,
    unit: "Nos",
    warranty: "01 Years",
    description:
      "Supply of Standard SKIMMER fitted on the wall of the pool.\n\nMAKE : PENTAIR / MIDAS / AQUATIX / AQVASTAR",
    imagePath: "/template-images/mr-swimming-pools/std-skimmer.png",
    poolTypeFilter: "skimmer",
    sortOrder: 11,
  },
  {
    id: "seed-temp-prod-9",
    name: "LABOUR CHARGES - PLANT ROOM & BASIN EQUIPMENTS",
    title: "LABOUR CHARGES - PLANT ROOM & BASIN EQUIPMENTS",
    section: "A",
    category: "PLANT ROOM EQUIPMENTS",
    serialNo: 12,
    defaultQty: 1,
    defaultRate: 25000,
    unit: "Lsm",
    warranty: "01 Years",
    description:
      "Installation charges for Plant room filtration equipments & pool inside and outside basin fittings etc.",
    imagePath: "/template-images/mr-swimming-pools/labour-charges--plant-room-and-basin-equipments.png",
    sortOrder: 12,
  },
  {
    id: "seed-temp-prod-10",
    name: "PLUMBING MATERIALS",
    title: "PLUMBING MATERIALS",
    section: "A",
    category: "PLANT ROOM EQUIPMENTS",
    serialNo: 13,
    defaultQty: 1,
    defaultRate: 145000,
    unit: "Lsm",
    warranty: "0",
    description:
      'Supply of required Heavy duty 10kg/6kg {{plumbingPipeSize}} PVC/UPVC pipes with required fittings for the Pool and filtration room between plumbing connections etc. All in pasting type.\n\nUPVC Pipes - Elbows - Tees - Shoes\nEnd Cap - MTA - FTA - Coupling - UPVC Solvent etc.\n\nSCH-40 UPVC pipe or 10 Kgf/cm2 PVC Pipe.\n\nMAKE : ASTRAL, SUPREME, FINOLEX etc.',
    templateVariables: ["plumbingPipeSize"],
    defaultVariableValues: { plumbingPipeSize: '1 1/2"' },
    imagePath: "/template-images/mr-swimming-pools/plumbing-materials.png",
    sortOrder: 13,
  },
  {
    id: "seed-temp-prod-11",
    name: "CONTROL & REGULATING EQUIPMENTS",
    title: "CONTROL & REGULATING EQUIPMENTS",
    section: "A",
    category: "PLANT ROOM EQUIPMENTS",
    serialNo: 14,
    defaultQty: 18,
    defaultRate: 3800,
    unit: "Nos",
    warranty: "01 Years",
    description:
      "Providing Supply of Imported Ball valves & NRV to the Pump & filter and Standard ball valves to the Connection Pipe Lines etc.\n\nMAKE : CEPEX - Spain or Equivalent.",
    imagePath: "/template-images/mr-swimming-pools/control-regulating-equipments-composite.png",
    sortOrder: 14,
  },
  {
    id: "seed-temp-prod-12",
    name: "LABOUR CHARGES - PLUMBING WORKS",
    title: "LABOUR CHARGES - PLUMBING WORKS",
    section: "A",
    category: "PLANT ROOM EQUIPMENTS",
    serialNo: 15,
    defaultQty: 1,
    defaultRate: 25000,
    unit: "Lsm",
    warranty: "01 Years",
    description:
      "Laying pipe lines throughout the pool till plant room for inlets, main drains, and vacuum points complete.",
    imagePath: "/template-images/mr-swimming-pools/labour-plumbing.png",
    sortOrder: 15,
  },
  {
    id: "seed-temp-prod-13",
    name: "UNDERWATER LIGHT",
    title: "UNDERWATER LIGHT",
    section: "A",
    category: "PLANT ROOM EQUIPMENTS",
    serialNo: 16,
    defaultQty: 14,
    defaultRate: 5800,
    unit: "Nos",
    warranty: "02 Years",
    description:
      "Providing & Laying of {{underwaterLightWattage}} LED underwater Lights with IP68 ratings.",
    templateVariables: ["underwaterLightWattage"],
    defaultVariableValues: { underwaterLightWattage: "24w/18v" },
    imagePath: "/template-images/mr-swimming-pools/underwater-light.png",
    sortOrder: 16,
  },
  {
    id: "seed-temp-prod-14",
    name: "ELECTRICAL MATERIALS",
    title: "ELECTRICAL MATERIALS",
    section: "B",
    category: "ELECTRICAL WORK",
    serialNo: 1,
    defaultQty: 1,
    defaultRate: 28000,
    unit: "Lsm",
    warranty: "0",
    description:
      "Supply of 1.5 Sqmm x 2 core Electrical cabling with required conduits for Pool pumps to the electrical panels with required clamping etc.\n\nMAKE: V Guard, Finolex, Havells, Polycab Etc.",
    imagePath: "/template-images/mr-swimming-pools/electrical-materials-composite.png",
    sortOrder: 17,
  },
  {
    id: "seed-temp-prod-15",
    name: "LABOUR CHARGES - POOL ELECTRICAL WORKS",
    title: "LABOUR CHARGES - POOL ELECTRICAL WORKS",
    section: "B",
    category: "ELECTRICAL WORK",
    serialNo: 2,
    defaultQty: 1,
    defaultRate: 25000,
    unit: "Lsm",
    warranty: "01 Years",
    description:
      "Labour charges for Installation of Electrical cabling with required conduits for to Electrical Panel & Pool pumps to the electrical panels with required clamping etc.\n\nMAKE: V Guard, Finolex, Havells, Polycab Etc.",
    imagePath: "/template-images/mr-swimming-pools/labour-charges--pool-electrical-works.png",
    sortOrder: 18,
  },
  {
    id: "seed-temp-prod-16",
    name: "POOL STARTER FOR PUMPS & LIGHTS",
    title: "POOL STARTER FOR PUMPS & LIGHTS",
    section: "C",
    category: "CONTROL PANEL",
    serialNo: 1,
    defaultQty: 2,
    defaultRate: 4500,
    unit: "Lsm",
    warranty: "01 Years",
    description: "Supply & fixing of Single Phase starter.",
    imagePath: "/template-images/mr-swimming-pools/pool-starter-for-pumps-and-lights.png",
    sortOrder: 19,
  },
  {
    id: "seed-temp-prod-17",
    name: "TRANSFORMER FOR UNDER WATER LIGHTS",
    title: "TRANSFORMER FOR UNDER WATER LIGHTS",
    section: "C",
    category: "CONTROL PANEL",
    serialNo: 2,
    defaultQty: 1,
    defaultRate: 10000,
    unit: "Nos",
    warranty: "01 YEARS",
    description: "AC TO DC CONVERTING {{voltage}} TRANSFORMER",
    templateVariables: ["voltage"],
    defaultVariableValues: { voltage: "12V" },
    imagePath: "/template-images/mr-swimming-pools/transformer-for-pool-lights.png",
    sortOrder: 20,
  },
  {
    id: "seed-temp-prod-18",
    name: "TESTING & COMMISSIONING OF THE POOL",
    title: "TESTING & COMMISSIONING OF THE POOL",
    section: "C",
    category: "CONTROL PANEL",
    serialNo: 3,
    defaultQty: 1,
    defaultRate: 25000,
    unit: "Lsm",
    warranty: "0",
    description:
      "After water filling testing, commissioning & running of the pool to ensure the proper running condition of the pool filtration system.",
    imagePath: "/template-images/mr-swimming-pools/testing-and-commissioning-of-the-pool.png",
    sortOrder: 21,
  },
  {
    id: "seed-temp-prod-19",
    name: "VACUUM HEAD",
    title: "VACUUM HEAD",
    section: "D",
    category: "CLEANING KIT",
    serialNo: 1,
    defaultQty: 1,
    defaultRate: 4500,
    unit: "Nos",
    warranty: "0",
    description:
      "Supply of Vacuum Head aluminum body with 4 wheels and brush etc.\n\nMAKE : PENTAIR / AQUATIX.",
    imagePath: "/template-images/mr-swimming-pools/vacuum-head.png",
    sortOrder: 22,
  },
  {
    id: "seed-temp-prod-20",
    name: "VACUUM HOSE",
    title: "VACUUM HOSE",
    section: "D",
    category: "CLEANING KIT",
    serialNo: 2,
    defaultQty: 1,
    defaultRate: 5500,
    unit: "Nos",
    warranty: "0",
    description:
      "Supply of Vacuum Hose {{hoseLength}} Length for the Pool Cleaning.\n\nMAKE : PENTAIR / AQUATIX.",
    templateVariables: ["hoseLength"],
    defaultVariableValues: { hoseLength: "15 Meter" },
    imagePath: "/template-images/mr-swimming-pools/vacuum-hose.png",
    sortOrder: 23,
  },
  {
    id: "seed-temp-prod-21",
    name: "TELESCOPIC ROD",
    title: "TELESCOPIC ROD",
    section: "D",
    category: "CLEANING KIT",
    serialNo: 3,
    defaultQty: 1,
    defaultRate: 5800,
    unit: "Nos",
    warranty: "0",
    description:
      "Supply of Telescopic rod {{rodLength}} length aluminium pole expandable type.\n\nMAKE : PENTAIR / AQUATIX.",
    templateVariables: ["rodLength"],
    defaultVariableValues: { rodLength: "9-27'" },
    imagePath: "/template-images/mr-swimming-pools/telescopic-rod.png",
    sortOrder: 24,
  },
  {
    id: "seed-temp-prod-22",
    name: "DEEP LEAF RAKE",
    title: "DEEP LEAF RAKE",
    section: "D",
    category: "CLEANING KIT",
    serialNo: 4,
    defaultQty: 1,
    defaultRate: 1400,
    unit: "Nos",
    warranty: "0",
    description: "Supply of Deep net for the pool cleaning.\n\nMAKE : PENTAIR / AQUATIX.",
    imagePath: "/template-images/mr-swimming-pools/deep-leaf-rake.png",
    sortOrder: 25,
  },
  {
    id: "seed-temp-prod-23",
    name: "WATER TEST KIT",
    title: "WATER TEST KIT",
    section: "D",
    category: "CLEANING KIT",
    serialNo: 5,
    defaultQty: 1,
    defaultRate: 700,
    unit: "Nos",
    warranty: "0",
    description:
      "Supply of Pool water Test Kit for pH and Chlorin.\n\nMAKE : PENTAIR / AQUATIX.",
    imagePath: "/template-images/mr-swimming-pools/water-test-kit.png",
    sortOrder: 26,
  },
  {
    id: "seed-temp-prod-24",
    name: "POOL BRUSH",
    title: "POOL BRUSH",
    section: "D",
    category: "CLEANING KIT",
    serialNo: 6,
    defaultQty: 1,
    defaultRate: 1400,
    unit: "Nos",
    warranty: "0",
    description:
      "Supply of Pool cleaning Brush with aluminium back.\n\nMAKE : PENTAIR / AQUATIX.",
    imagePath: "/template-images/mr-swimming-pools/pool-brush.png",
    sortOrder: 27,
  },
  {
    id: "seed-temp-prod-25",
    name: "POOL CHEMICALS",
    title: "POOL CHEMICALS",
    section: "D",
    category: "CLEANING KIT",
    serialNo: 7,
    defaultQty: 1,
    defaultRate: 10000,
    unit: "Lsm",
    warranty: "0",
    description:
      "Initial Supply of Pool Chemicals like TCCA 90, Algaecide, pH Balancing Chemicals etc for initial Pool cleaning etc.",
    imagePath: "/template-images/mr-swimming-pools/pool-chemicals.png",
    sortOrder: 28,
  },
  {
    id: "seed-temp-prod-26",
    name: "WATER PROOFING",
    title: "WATER PROOFING",
    section: "Part 2",
    category: "POOL FINISHES",
    serialNo: 1,
    defaultQty: 4062,
    defaultRate: 55,
    unit: "Lsm",
    warranty: "05 Years",
    description:
      "Supply and applying of ELESTO-MERICO Two coat weather proof high flexibility cementitious mortar with crack bridging capacity up to 2mm, Edge band for all the corners for swimming pools, Balancing Tank, Filtration room & overflow Gutter.\n\nMAKE : NIPPON/MAPEI/KERAKOLL/MYK",
    imagePath: "/template-images/mr-swimming-pools/waterproofing.png",
    sortOrder: 29,
  },
  {
    id: "seed-temp-prod-27",
    name: "COPING STONE: LABOR CHARGES ONLY",
    title: "COPING STONE: LABOR CHARGES ONLY",
    section: "Part 2",
    category: "POOL FINISHES",
    serialNo: 2,
    defaultQty: 396,
    defaultRate: 80,
    unit: "Sft",
    warranty: "0",
    description:
      "Labor charges for fixing of 20mm thick Granite stone as coping stone and nosing etc. (**Excluding Granite/cement)\n\nMAKE: SADARAHALLI / BANGALORE STONE.",
    imagePath: "/template-images/mr-swimming-pools/coping-stone.png",
    sortOrder: 30,
  },
  {
    id: "seed-temp-prod-28",
    name: "SWIMMING POOL TILES",
    title: "SWIMMING POOL TILES",
    section: "Part 2",
    category: "POOL FINISHES",
    serialNo: 3,
    defaultQty: 2730,
    defaultRate: 90,
    unit: "Sft",
    warranty: "0",
    description:
      "Supply of RECTIFIED 12X12 INCHES tiles standard colour for the floor and walls of the pool.\n\nMAKE : ",
    imagePath: "/template-images/mr-swimming-pools/swimming-pool-tiles.png",
    sortOrder: 31,
  },
  {
    id: "seed-temp-prod-29",
    name: "LABOUR CHARGES - TILES FIXING & GROUTING",
    title: "LABOUR CHARGES - TILES FIXING & GROUTING",
    section: "Part 2",
    category: "POOL FINISHES",
    serialNo: 4,
    defaultQty: 2730,
    defaultRate: 90,
    unit: "Sft",
    warranty: "01 Year for Tiles Fixing",
    description:
      "Labour charges for Tiles fixing & Grouting with required Tools and materials for cleaning after Grouting etc.",
    imagePath: "/template-images/mr-swimming-pools/tile-fixing-labour.png",
    sortOrder: 32,
  },
];

export function getMRProductDefinition(id: string): MRProductDefinition | undefined {
  return MR_PRODUCT_DEFINITIONS.find((p) => p.id === id);
}
